using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class PlayerMotor : MonoBehaviour {
	Transform target;
	NavMeshAgent agent; 


	// Use this for initialization, its from git
	void Start () {

		agent = GetComponent<NavMeshAgent> ();

	}
	void Update () 
	{
		if (target != null) 
		{
			agent.SetDestination (target.position);
			FaceTarget ();
		}
	}
	public void  MoveToPoint (Vector3 point) 
	{

		agent.SetDestination (point);

	}
	public void FollowTarget (Interactable newtarget) 
	{
		agent.stoppingDistance = newtarget.radius * 0.8f;
		agent.updateRotation = false; 
		target = newtarget.interactionTransform; 

	}

	public void StopFollowingTarget () 
	{
		agent.stoppingDistance = 0f;
		agent.updateRotation = true;
		target = null;


	}
	void FaceTarget () 
	{
		Vector3 direction = (target.position - transform.position).normalized;
		Quaternion lookRotation = Quaternion.LookRotation (new Vector3 (direction.x, 0f, direction.z));
		transform.rotation = Quaternion.Slerp (transform.rotation, lookRotation, Time.deltaTime * 5f);
	}

}
